FROM windowskonon1337/cleversearch_mlcore_core

COPY ./Services/AudioService/requirements.txt /

RUN pip install -r /requirements.txt && rm /requirements.txt && \
    apt-get update && apt-get install ffmpeg -y

COPY . /app/MLCore

CMD ["python", "/app/MLCore/Services/AudioService/__main__.py"]